// cardTemplates.js - Create this file to store all card templates

export const cardTemplates = [
  {
    id: "professional",
    name: "Professional",
    description: "Clean and professional design for business use",
    theme: "blue",
    fontStyle: "sans-serif",
    backgroundType: "color",
    buttonStyle: "rounded",
    socialIconStyle: "circle",
    preview: "/templates/professional.jpg",
  },
  {
    id: "creative",
    name: "Creative",
    description: "Bold and colorful design for creative professionals",
    theme: "purple",
    fontStyle: "sans-serif",
    backgroundType: "gradient",
    backgroundImage: "linear-gradient(135deg, #8e24aa 0%, #b39ddb 100%)",
    buttonStyle: "pill",
    socialIconStyle: "rounded",
    preview: "/templates/creative.jpg",
  },
  {
    id: "minimalist",
    name: "Minimalist",
    description: "Simple and elegant design with clean layout",
    theme: "dark",
    fontStyle: "sans-serif",
    backgroundType: "color",
    buttonStyle: "square",
    socialIconStyle: "subtle",
    preview: "/templates/minimalist.jpg",
  },
  {
    id: "nature",
    name: "Nature",
    description: "Calm and natural design with earthy tones",
    theme: "green",
    fontStyle: "serif",
    backgroundType: "image",
    backgroundImage:
      "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=600&auto=format&fit=crop",
    buttonStyle: "soft",
    socialIconStyle: "circle",
    preview: "/templates/nature.jpg",
  },
  {
    id: "tech",
    name: "Tech",
    description: "Modern and sleek design for tech professionals",
    theme: "teal",
    fontStyle: "monospace",
    backgroundType: "pattern",
    backgroundImage:
      "url('https://www.transparenttextures.com/patterns/gplay.png')",
    buttonStyle: "angular",
    socialIconStyle: "square",
    preview: "/templates/tech.jpg",
  },
  {
    id: "elegant",
    name: "Elegant",
    description: "Sophisticated and luxurious design",
    theme: "dark",
    fontStyle: "serif",
    backgroundType: "gradient",
    backgroundImage: "linear-gradient(135deg, #424242 0%, #757575 100%)",
    buttonStyle: "rounded",
    socialIconStyle: "subtle",
    preview: "/templates/elegant.jpg",
  },
  {
    id: "vibrant",
    name: "Vibrant",
    description: "Energetic and lively design with bold colors",
    theme: "orange",
    fontStyle: "sans-serif",
    backgroundType: "gradient",
    backgroundImage: "linear-gradient(135deg, #ff7043 0%, #ffcc80 100%)",
    buttonStyle: "pill",
    socialIconStyle: "circle",
    preview: "/templates/vibrant.jpg",
  },
  {
    id: "corporate",
    name: "Corporate",
    description: "Traditional corporate design for executives",
    theme: "blue",
    fontStyle: "serif",
    backgroundType: "pattern",
    backgroundImage:
      "url('https://www.transparenttextures.com/patterns/diamond-upholstery.png')",
    buttonStyle: "square",
    socialIconStyle: "subtle",
    preview: "/templates/corporate.jpg",
  },
];
